language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: "kennycyb"
    token:
      secure: ho0+QzCSZB8i3nmydyBTA8hJuEpiHfbdkAm3VnmbOHO5Z6RL99VO9Pz1AO9N15fsv9ktVkb7n4aUwj4kq+6oCF/SPN8nTscMzX3fpu/0EfBxahh2vUMDg/VdxNjPZ8rKZhpyftGnyIX+LCRfvGJgAQ6Sgrr6HXkVtL08W0+pJqM=


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=kennycyb_java-ui-factory
